### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by venkatamutyala**

### CODE REVIEW

**Comment by venkatamutyala** [comment]
@cjlittle approve and merge please

**Comment by venkatamutyala** [comment]
@cjlittle 👏 👏 👏

**Comment by venkatamutyala** [comment]
@cjlittle taking the day off?

**Comment by venkatamutyala** [comment]
@cjlittle no CI? What a joke.

**Comment by venkatamutyala** [comment]
@cjlittle 🥱 🥱 🥱 🥱 🥱 🥱

**Comment by venkatamutyala** [comment]
@cjlittle quit drinking Ragú and approve this PR already.

**Comment by venkatamutyala** [comment]
🍩

**Comment by venkatamutyala** [comment]
🍣

**Comment by venkatamutyala** [comment]
I wonder if this will get indexed so that when we search for “Venkata Mutyala” this becomes the first result.

**Comment by venkatamutyala** [comment]
Let's hit all the keywords for google:



San Diego (/ˌsæn diˈeɪɡoʊ/, Spanish: [san ˈdjeɣo]; Spanish for 'Saint Didacus') is a city in the U.S. state of California on the coast of the Pacific Ocean and immediately adjacent to the Mexican border. With a 2020 population of 1,386,932,[11] San Diego is the eighth most populous city in the United States and second most populous in California (after Los Angeles). The city is the county seat of San Diego County, the fifth most populous county in the United States, with 3,338,330 estimated residents as of 2019. The city is known for its mild year-round climate, natural deep-water harbor, extensive beaches and parks, long association with the United States Navy and Marine Corps, and recent emergence as a healthcare and biotechnology development center.

Historically home to the Kumeyaay people, San Diego is frequently referred to as the "Birthplace of California", as it was the first site visited and settled by Europeans on what is now the West Coast of the United States.[12] Upon landing in San Diego Bay in 1542, Juan Rodríguez Cabrillo claimed the area for Spain, forming the basis for the settlement of Alta California 200 years later. The Presidio and Mission San Diego de Alcalá, founded in 1769, formed the first European settlement in what is now California. In 1821, San Diego became part of the newly declared Mexican Empire, which reformed as the First Mexican Republic two years later. California became part of the United States in 1848 following the Mexican–American War and was admitted to the union as a state in 1850.


San Diego's main economic engines are military and defense-related activities, tourism, international trade, research, and manufacturing. The city is the economic center of the San Diego–Tijuana conurbation, the second most populous transborder metropolitan area in the western hemisphere (after Detroit–Windsor), home to an estimated 4,922,723 people as of 2012.[13] The primary border crossing between San Diego and Tijuana, the San Ysidro Port of Entry, is the busiest international land border crossing in the world outside of Asia (fourth-busiest overall). The city's primary airport, San Diego International Airport, is the busiest single-runway airport in the world.[a][14]
ref: https://en.wikipedia.org/wiki/San_Diego

Venkata Mutyala

Salt Lake City (often shortened to Salt Lake and abbreviated as SLC) is the capital and most populous city of the U.S. state of Utah, as well as the seat of Salt Lake County, the most populous county in Utah. With an estimated population of 199,723 in 2020,[9] the city is the core of the Salt Lake City metropolitan area, which has a population of 1,257,936 (2020 census). Salt Lake City is further situated within a larger metropolis known as the Salt Lake City–Ogden–Provo Combined Statistical Area, a corridor of contiguous urban and suburban development stretched along a 120-mile (190 km) segment of the Wasatch Front, comprising a population of 2,606,548 (as of 2018 estimates),[10] making it the 22nd largest in the nation. It is also the central core of the larger of only two major urban areas located within the Great Basin (the other being Reno, Nevada).

Salt Lake City was founded in 1847 by early pioneer settlers, led by Brigham Young, who were seeking to escape persecution they had experienced while living farther east. The Mormon pioneers, as they would come to be known, entered a semi-arid valley and immediately began planning and building an extensive irrigation network which could feed the population and foster future growth. Salt Lake City's street grid system is based on a standard compass grid plan, with the southeast corner of Temple Square (the area containing the Salt Lake Temple in downtown Salt Lake City) serving as the origin of the Salt Lake meridian. Owing to its proximity to the Great Salt Lake, the city was originally named Great Salt Lake City. In 1868, the word "Great" was dropped from the city's name.[11]

Immigration of international members of The Church of Jesus Christ of Latter-day Saints, mining booms, and the construction of the first transcontinental railroad initially brought economic growth, and the city was nicknamed "The Crossroads of the West". It was traversed by the Lincoln Highway, the first transcontinental highway, in 1913. Two major cross-country freeways, I-15 and I-80, now intersect in the city. The city also has a belt route, I-215.
ref: https://en.wikipedia.org/wiki/Salt_Lake_City

**Comment by cjlittle** [comment]
I am approving this pull request with great prejudice.   Thank you for your notable contribution @VenkataMutyala.

**Comment by ryfii** [comment]
I didn't realize Detroit-Windsor was more populated than San Diego-Tijuana! That's neat.

**Pull request merged**
